export const h1 = "scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-balance"
export const h2 = "scroll-m-20 pb-2 text-3xl font-semibold tracking-tight first:mt-0"
export const h3 = "scroll-m-20 text-2xl font-semibold tracking-tight"
export const h4 = "scroll-m-20 text-xl font-semibold tracking-tight"
export const p = "leading-7 [&:not(:first-child)]:mt-2 select-text"
export const blockQuote = "mt-6 border-l-2 pl-6 italic"
export const inlineCode = "bg-muted relative rounded px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold"
